name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace name'
        required: true
        default: 'dev'

env:
  TF_WORKSPACE: ${{ github.event.inputs.workspace }}
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ghoten
        uses: vmvarela/ghoten/actions/setup@master
      
      - name: Ghoten Init
        run: ghoten init
      
      - name: Ghoten Plan
        run: ghoten plan -out=tfplan
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
      
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ inputs.workspace }}
          path: tfplan
