name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace name'
        required: true
        default: 'dev'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ghoten
        uses: vmvarela/ghoten/actions/setup@v1.11.2
      
      - name: Ghoten Init
        run: ghoten init
      
      - name: Ghoten Apply
        run: ghoten apply -auto-approve
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
